#include "catch.hpp"
#include "decide_local_nli.hpp"
#include "decide_tokenizer.hpp"

#include <cstdlib>

using namespace duckdb;
using namespace duckdb::anofox;
using Catch::Matchers::Contains;

TEST_CASE("tiny BPE tokenizer mechanics", "[anofox_decide][tokenizer]") {
	DecideTokenizer tok;
	tok.Load("test/fixtures/tiny_tokenizer.json");
	REQUIRE(tok.Loaded());
	REQUIRE(tok.Specials().mask == 3);
	REQUIRE(tok.Specials().cls == 2);
	REQUIRE(tok.Specials().sep == 1);
	REQUIRE(tok.Specials().pad == 0);

	SECTION("prepend-always makes leading space insignificant") {
		// "ab" and " ab" both normalize to pieces ["▁ab"]: rank-0 (▁,a)
		// merges to [▁a, b]; (▁a,b) has no rule.
		REQUIRE(tok.Encode("ab") == std::vector<int32_t> {9, 7});
		REQUIRE(tok.Encode(" ab") == std::vector<int32_t> {9, 7});
	}
	SECTION("multi-round merges") {
		// "aab" -> [▁a, ab]: (▁,a) first, then (a,b).
		REQUIRE(tok.Encode("aab") == std::vector<int32_t> {9, 10});
	}
	SECTION("empty input") {
		REQUIRE(tok.Encode("").empty());
	}
	SECTION("special tokens split longest-first, never BPE'd") {
		REQUIRE(tok.Encode("<mask>") == std::vector<int32_t> {3});
		// Each post-split span is pretokenized independently, so "a" still
		// gets its prepended boundary: [▁a, <mask>] (verified against HF
		// on the Julia tokenizer: "a<mask>" -> ["▁a", <mask>]).
		REQUIRE(tok.Encode("a<mask>") == std::vector<int32_t> {9, 3});
	}
	SECTION("missing file is actionable") {
		DecideTokenizer bad;
		REQUIRE_THROWS_WITH(bad.Load("test/fixtures/does-not-exist.json"), Contains("not found"));
	}
}

TEST_CASE("Julia-1 tokenizer matches HF goldens", "[anofox_decide][tokenizer]") {
	const char *weights = std::getenv("JULIA_WEIGHTS_DIR");
	if (!weights) {
		WARN("skipped (needs JULIA_WEIGHTS_DIR: 34MB tokenizer.json, not committed)");
		return;
	}
	DecideTokenizer tok;
	tok.Load(std::string(weights) + "/tokenizer/tokenizer.json");
	// The live HF tokenizer reports cls=2 (<bos>), NOT the encoder
	// config's cls_token_id=1 — the port must follow HF.
	REQUIRE(tok.Specials().cls == 2);
	REQUIRE(tok.Specials().sep == 1);
	REQUIRE(tok.Specials().mask == 4);
	REQUIRE(tok.Specials().pad == 0);
	REQUIRE(tok.Specials().mask_token == "<mask>");
	REQUIRE(tok.VocabSize() == 256000);

	// Full encode corpus from the golden file
	// (test/fixtures/julia_tokenizer_golden.json, generated by the live HF
	// tokenizer — authoritative, including multibyte byte-fallback).
	REQUIRE(tok.Encode("A refund is requested.") ==
	        std::vector<int32_t> {586, 19745, 603, 16350, 235265});
	REQUIRE(tok.Encode(" billing") == std::vector<int32_t> {54972});
	REQUIRE(tok.Encode("Which team owns this?") ==
	        std::vector<int32_t> {12236, 2970, 33241, 736, 235336});
	REQUIRE(tok.Encode("My invoice charges twice the agreed amount.") ==
	        std::vector<int32_t> {2961, 42529, 12036, 11594, 573, 11327, 3619, 235265});
	REQUIRE(tok.Encode("choice question: A refund is requested.") ==
	        std::vector<int32_t> {6241, 2872, 235292, 586, 19745, 603, 16350, 235265});
	REQUIRE(tok.Encode("Rückerstattung angefordert.") ==
	        std::vector<int32_t> {79095, 4185, 58578, 25278, 122015, 235265});
	REQUIRE(tok.Encode("") == std::vector<int32_t> {});
	// SentencePiece <0xXX> byte fallback (HF goldens): unknown characters
	// split into byte tokens, not GPT-style byte-level glyphs.
	REQUIRE(tok.Encode("\xC6\xB9") == std::vector<int32_t> {235248, 415, 402});
	REQUIRE(tok.Encode("Refund \xF0\x9F\x99\x8F please") == std::vector<int32_t> {93114, 68226, 3743});
	REQUIRE(tok.Encode("Ticket #4711 \xE2\x80\x94 Stra\xC3\x9F" "e") ==
	        std::vector<int32_t> {40624, 1700, 235310, 235324, 235274, 235274, 2062, 52721});
}

TEST_CASE("Julia-1 collation matches upstream data.sequence goldens", "[anofox_decide][tokenizer]") {
	const char *weights = std::getenv("JULIA_WEIGHTS_DIR");
	if (!weights) {
		WARN("skipped (needs JULIA_WEIGHTS_DIR: 34MB tokenizer.json, not committed)");
		return;
	}
	DecideTokenizer tok;
	tok.Load(std::string(weights) + "/tokenizer/tokenizer.json");
	const duckdb::vector<string> opts = {"billing", "defect", "other"};

	// Goldens produced by upstream julia.data.sequence (strict=False,
	// max_length=8192) with the live HF tokenizer.
	std::vector<int32_t> plain = {2,      6241,   2872,  235292, 12236, 2970,  33241, 736,   235336, 1,
	                              4,      54972,  4,     37730,  4,     1156,  1,     590,   729,    12497,
	                              11594,  604,    970,   4482,   42529, 235269, 3743,  19745, 573,    3437,
	                              235248, 235310, 235315, 34228, 235265, 1};
	auto row = DecideCollateRow(tok, "I was charged twice for my March invoice, please refund the extra 49 EUR.",
	                            "Which team owns this?", opts, 0, 8192, 512);
	REQUIRE(std::vector<int32_t>(row.ids.begin(), row.ids.end()) == plain);
	REQUIRE(row.markers == duckdb::vector<int64_t> {10, 12, 14});

	std::string long_q;
	for (int i = 0; i < 60; i++) {
		long_q += "word ";
	}
	long_q += "?";
	auto lr = DecideCollateRow(tok, "Ticket #4711 \xE2\x80\x94 Stra\xC3\x9F"
	                                "e \xC6\xB9 \xF0\x9F\x99\x8F",
	                           long_q, opts, 0, 8192, 24);
	// head cut to max(8, head_length - options) = 17 tokens after the
	// 4-token "choice question:" prefix... upstream keeps 15 "word" tokens.
	std::vector<int32_t> golden_b24 = {2,     6241,  2872,  235292, 2204,  2204,   2204, 2204,  2204,  2204,
	                                   2204,  2204,  2204,  2204,   2204,  2204,   2204, 2204,  2204,  1,
	                                   4,     54972, 4,     37730,  4,     1156,   1,    40624, 1700,  235310,
	                                   235324, 235274, 235274, 2062, 52721, 235248, 415,  402,   68226, 1};
	REQUIRE(std::vector<int32_t>(lr.ids.begin(), lr.ids.end()) == golden_b24);
	REQUIRE(lr.markers == duckdb::vector<int64_t> {20, 22, 24});
}
