# Embed the weight-free graphs and tensor maps in resources/ into the extension.
#
# Generates ${CMAKE_CURRENT_BINARY_DIR}/decide_bundled_resources.cpp implementing
# DecideGetBundledResource() (src/include/decide_bundled_resources.hpp) from the
# committed files, so the local models need no companion graph on disk. The
# bytes carry no model weights: graphs hold external-data stubs, maps are name
# mappings (tools/export_julia, enforced by .github/workflows/graph_invariants.yml).
#
# Every file is registered under its file name; graphs also under their bare
# stem ("graph_laya-multilingual"). Hex-array embedding builds with GCC, Clang
# and MSVC alike (same method as anofox-tabfm).
#
# Output: sets DECIDE_BUNDLED_RESOURCES_SRC to the generated source path.

set(_decide_res_dir "${CMAKE_CURRENT_SOURCE_DIR}/resources")
set(_decide_gen "${CMAKE_CURRENT_BINARY_DIR}/decide_bundled_resources.cpp")
set(_decide_inputs
    "graph_julia-1.onnx"
    "graph_laya-multilingual.onnx"
    "graph_laya-typed-decisions.onnx"
    "tensor_map_julia-1.json"
    "tensor_map_laya-multilingual.json"
    "tensor_map_laya-typed-decisions.json")

foreach(_f ${_decide_inputs})
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_decide_res_dir}/${_f}")
endforeach()

# Regenerate when missing or stale; a change to this file counts too.
set(_decide_stale FALSE)
if(NOT EXISTS "${_decide_gen}")
    set(_decide_stale TRUE)
elseif("${CMAKE_CURRENT_LIST_FILE}" IS_NEWER_THAN "${_decide_gen}")
    set(_decide_stale TRUE)
else()
    foreach(_f ${_decide_inputs})
        if("${_decide_res_dir}/${_f}" IS_NEWER_THAN "${_decide_gen}")
            set(_decide_stale TRUE)
        endif()
    endforeach()
endif()

if(_decide_stale)
    message(STATUS "anofox_decide: embedding resources -> ${_decide_gen}")
    set(_body "// Generated by cmake/embed_resources.cmake - do not edit.\n")
    string(APPEND _body "#include \"decide_bundled_resources.hpp\"\n\n")
    string(APPEND _body "namespace duckdb {\nnamespace anofox {\nnamespace {\n\n")
    set(_idx 0)
    set(_table "")
    foreach(_f ${_decide_inputs})
        set(_path "${_decide_res_dir}/${_f}")
        if(NOT EXISTS "${_path}")
            message(FATAL_ERROR "anofox_decide: bundled resource missing: ${_path}")
        endif()
        file(READ "${_path}" _hex HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
        string(APPEND _body "static const unsigned char kRes${_idx}[] = {${_arr}};\n\n")
        string(APPEND _table "    {\"${_f}\", kRes${_idx}, sizeof(kRes${_idx})},\n")
        if(_f MATCHES "\\.onnx$")
            string(REGEX REPLACE "\\.onnx$" "" _stem "${_f}")
            string(APPEND _table "    {\"${_stem}\", kRes${_idx}, sizeof(kRes${_idx})},\n")
        endif()
        math(EXPR _idx "${_idx}+1")
    endforeach()
    string(APPEND _body "struct BundledEntry {\n    const char *id;\n    const unsigned char *data;\n    unsigned long size;\n};\n\n")
    string(APPEND _body "const BundledEntry kBundled[] = {\n${_table}};\n\n} // namespace\n\n")
    string(APPEND _body "DecideBundledResource DecideGetBundledResource(const string &id) {\n")
    string(APPEND _body "\tfor (const auto &e : kBundled) {\n\t\tif (id == e.id) {\n")
    string(APPEND _body "\t\t\treturn DecideBundledResource {reinterpret_cast<const char *>(e.data), static_cast<idx_t>(e.size)};\n")
    string(APPEND _body "\t\t}\n\t}\n\treturn DecideBundledResource {nullptr, 0};\n}\n\n")
    string(APPEND _body "} // namespace anofox\n} // namespace duckdb\n")
    file(WRITE "${_decide_gen}" "${_body}")
endif()

set(DECIDE_BUNDLED_RESOURCES_SRC "${_decide_gen}")
