//===----------------------------------------------------------------------===//
// decide_bundled_resources.hpp — weight-free graphs and tensor maps compiled
// into the extension (generated by cmake/embed_resources.cmake from resources/).
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/common/common.hpp"

namespace duckdb {
namespace anofox {

//! Read-only view of a resource in static storage (process lifetime).
struct DecideBundledResource {
	const char *data = nullptr;
	idx_t size = 0;
};

//! The resource registered under `id` ("graph_laya-multilingual", the file
//! name "graph_laya-multilingual.onnx", or "tensor_map_laya-multilingual.json");
//! {nullptr, 0} when unknown. A filesystem path never matches.
DecideBundledResource DecideGetBundledResource(const string &id);

} // namespace anofox
} // namespace duckdb
